### ISSUE TITLE
Adapter for Nette\DI\Container?

### ISSUE THREAD

**Issue by TomasVotruba** [gephart/dependency-injection#2]
I'd like to try this container with Nette\DI\Container.

I would appreciate your help with that.

I guess it would take to override [`createContainer()`](https://github.com/nette/bootstrap/blob/fc7d088304f1ceb744d1b909a64e5b37909367c7/src/Bootstrap/Configurator.php#L217-L226) method.

And probably extend `Container` with overriding `getService()` method: https://github.com/nette/di/blob/master/src/DI/Container.php#L18

**Comment by MichalKatuscak** [comment]
Hi and thank you for the thread!
I'd like to help.
But, I do not quite understand what you want to achieve. Why do you want to connect two DI containers?

**Comment by TomasVotruba** [comment]
I would like to use Nette DI Container, but just drop extensions and service registration.

**Comment by TomasVotruba** [comment]
I switched to Symfony
